// <auto-generated />
using System;
using LojaAmigurumi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LojaAmigurumi.Data.Migrations
{
    [DbContext(typeof(PatternDbContext))]
    partial class PatternDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LojaAmigurumi.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("CategoriaDescricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("LojaAmigurumi.Models.Nivel", b =>
                {
                    b.Property<int>("NivelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NivelId"));

                    b.Property<string>("NivelDescricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NivelId");

                    b.ToTable("Nivel", (string)null);
                });

            modelBuilder.Entity("LojaAmigurumi.Models.Pattern", b =>
                {
                    b.Property<int>("PatternId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatternId"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int?>("NivelId")
                        .HasColumnType("int");

                    b.Property<string>("PatternDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PatternImageUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatternName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("PatternPrice")
                        .HasColumnType("float");

                    b.HasKey("PatternId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("NivelId");

                    b.ToTable("Pattern", (string)null);
                });

            modelBuilder.Entity("LojaAmigurumi.Models.Pattern", b =>
                {
                    b.HasOne("LojaAmigurumi.Models.Categoria", null)
                        .WithMany("Patterns")
                        .HasForeignKey("CategoriaId");

                    b.HasOne("LojaAmigurumi.Models.Nivel", null)
                        .WithMany("Patterns")
                        .HasForeignKey("NivelId");
                });

            modelBuilder.Entity("LojaAmigurumi.Models.Categoria", b =>
                {
                    b.Navigation("Patterns");
                });

            modelBuilder.Entity("LojaAmigurumi.Models.Nivel", b =>
                {
                    b.Navigation("Patterns");
                });
#pragma warning restore 612, 618
        }
    }
}
